### ISSUE TITLE
data used in book not found in repo

### ISSUE THREAD

**Issue by vhphan** [reuven/pandas-workout#2]
Cannot find this file anywhere, 2020_sharing_data_outside.csv .

**Comment by SnehashisWalk** [comment]
Hey man, so far I found this book great!!
If you did not get the data folder for the exercises here is the link, its mentioned in the README as well
These are the Jupyter notebooks for my book, Pandas Workout. The data for the exercises are stored separately, at https://files.lerner.co.il/pandas-workout-data.zip .

**Comment by reuven** [comment]
Whoops -- I hadn't noticed that this comment hadn't been responded to, so thanks so much @SnehashisWalk for responding, and for the kind words about the book!
