### ISSUE TITLE
chapter-02/Exercise 12b — Beyond the exercise.ipynb (Beyond 2)

### ISSUE THREAD

**Issue by zarify** [reuven/pandas-workout#4]
> **How many short, medium, and long trips were there for trips that had only one passenger? Note that data for passenger count and trip length are from the same data set, meaning that the indexes are the same.**
> 
> If we're only interested in removing the non-outlier values, then we could use the scipy.stats.trimboth function on our series. It takes a second argument, the proportion we want to cut from both the top and bottom.

The first paragraph (emphasis) has nothing to do with removing the values outside of the top and bottom 10% cutoffs, and looks like it's a dupe of the Beyond 2 question from Exercise 7 from Chapter 1.

This also appears in the (at least Apple Books) edition of the text.

**Comment by reuven** [comment]
Thanks for your comment! I'll pass it along to Manning, and will try to fix it when we do another edition.
