### ISSUE TITLE
chapter-02/Exercise 14b — Beyond the exercise.ipynb (Beyond 2)

### ISSUE THREAD

**Issue by zarify** [reuven/pandas-workout#5]
The suggested solution for the Beyond 2 task does not match the description (emphasis mine):

> Set the **even** temperatures at hours 9 and 18 to 3

Whereas the solution sets all the temperatures at hours 9 and 18, not just the even ones:

```python
df.loc[
    df['hour'].isin([9, 18]), 
    'temp'] = 3
```

Shouldn't it be something like this instead?

```python
df.loc[
    (df['temp'] % 2 == 0) & df['hour'].isin([9, 18]),
    'temp'
] = 3
```

**Comment by reuven** [comment]
Thanks for your comment! I'll pass it along to Manning, and will try to fix it when we do another edition.
